name: Drift Detection (Nightly)

on:
  schedule:
    - cron: "23 1 * * *"   # 01:23 UTC nightly
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  issues: write

env:
  NODE_VERSION: "20"

jobs:
  drift:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ dev, stage, prod ]
        cloud: [ aws, gcp ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: ${{ env.NODE_VERSION }} }
      - run: npm ci

      - name: AWS OIDC
        if: matrix.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GHA_OIDC_ROLE_${{ matrix.env }}>
          aws-region: eu-west-1

      - name: GCP OIDC
        if: matrix.cloud == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/<PROJECT_NUMBER>/locations/global/workloadIdentityPools/<POOL>/providers/<PROVIDER>
          service_account: gha-magi-${{ matrix.env }}@<GCP_PROJECT_ID>.iam.gserviceaccount.com

      - name: Plan (no apply)
        id: plan
        continue-on-error: true
        run: npx magi plan --env ${{ matrix.env }} --cloud ${{ matrix.cloud }}

      - name: File drift issue if needed
        if: steps.plan.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Drift detected: ${context.payload.repository.full_name} (${ '${{ matrix.env }}' }/${ '${{ matrix.cloud }}'})`;
            const body = 'Nightly drift run failed planning. Investigate and reconcile.';
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner, repo: context.repo.repo, state: 'open'
            });
            if (!issues.find(i => i.title === title)) {
              await github.rest.issues.create({
                owner: context.repo.owner, repo: context.repo.repo,
                title, body, labels: ['infra','drift']
              });
            }
